### PR TITLE
Update README.md with specific insructions for creating a chatAdapter that works with a BotFramework-WebChat via DirectLine

### PR DESCRIPTION
**Pull request by adam-boosted**
Copilot Sutdio Instructions

# PR Details

### Description

I was wrapping a copilot studio bot (rendered with the webchat sdk) with the chat adapater and found myself unable to send events using the webchat APIs (received a `POST_ACTIVITY_IMPEDED` which should be due to a [timeout](https://github.com/microsoft/BotFramework-WebChat/blob/1d59ded74eb447b09c87469ba9813be728a38692/packages/core/src/sagas/postActivitySaga.ts#L151)) and getting prompted immediately that the chat was getting handed off to an agent upon instantiation.

Upon further investigation, by reading the code in this repository, I found that I needed to pass the parameters in this README (`secret`, `token`, `conversationId`, `conversationStartProperties`, etc) at which point sending events with webchat APIs no longer timed out, and I was no longer receiving a message that a transfer to an agent had begun, at instantiation of my bot.

I thought this information could be helpful for other users

## Solution Proposed

_Detail what is the solution proposed, include links to design document if required or any other document required to support the solution_

### Acceptance criteria

_Define what are the conditions to consider the PR has achieved the intended goal_

## Test cases and evidence

_Include what tests cases were considered, any evidence of testing for future references, to identify any corner cases, etc_

### Sanity Tests

- [ ] You have tested all changes in Popout mode
- [ ] You have tested all changes in cross browsers i.e Edge, Chrome, Firefox, Safari and mobile devices(iOS and Android)
- [ ] Your changes are included in the [CHANGELOG](../CHANGE_LOG.md)

## A11y

- [ ] You have run the [Automated Accessibility Check](https://accessibilityinsights.io/docs/en/windows/getstarted/automatedchecks) and have no reported issues

***Please provide justification if any of the validations has been skipped.***

### CODE REVIEW

**Comment by xTEddie** [comment]
Will the Copilot Studio bot be integrated with Omnichannel for Customer Service?

If not, I'd suggest to use [BotFramework-DirectLineJS](https://github.com/Microsoft/BotFramework-DirectLineJS) to integrate with Copilot Studio to use with WebChat.

OmnichannelChatSDK is built to support Omnichannel for Customer Service only.

Using simply `DirectLineJS` with the OmnichannelChatSDK would defeat the purpose of this SDK. `DirectLineJS` support was initially added to support a feature. However, the feature was deprioritized.

There's plans to remove `DirectLineJS` from OmnichannelChatSDK given the feature has been deprioritized.

**Comment by adam-boosted** [comment]
> Will the Copilot Studio bot be integrated with Omnichannel for Customer Service?

Yes. From all communication with microsoft and from reading all it's available documentation (including the README in this repository), having a copilot studio serving as the frontend for omnichannel should be a supported feature, but it's not working.

@xTEddie, implementation aside, the ultimate goal that I'm trying to implement is having a user interacting with a **Copilot Studio** chatbot be able to escalate/handoff the interaction to a human agent in **Dynamics 365**. 

I've been in touch with a Microsoft support engineer and I have this quote:

> According to our internal documents and knowledge base, currently, the new PVA2 platform integration with Dynamics 365 Omnichannel for Customer Service isn't available. However, you can still achieve this by creating a classic PVA bot.

Do you know if this means that Copilot Studio is unable to handoff to Dynamics 365 at all right now?

**Comment by xTEddie** [comment]
> > Will the Copilot Studio bot be integrated with Omnichannel for Customer Service?
> 
> Yes. From all communication with microsoft and from reading all it's [available documentation](https://learn.microsoft.com/en-us/microsoft-copilot-studio/configuration-hand-off-omnichannel?tabs=webApp#connect-your-copilot-to-omnichannel-for-customer-service) (including the README in this repository), having a copilot studio serving as the frontend for omnichannel should be a supported feature, but it's not working.
> 
> @xTEddie, implementation aside, the ultimate goal that I'm trying to implement is having a user interacting with a **Copilot Studio** chatbot be able to escalate/handoff the interaction to a human agent in **Dynamics 365**.
> 
> I've been in touch with a Microsoft support engineer and I have this quote:
> 
> > According to our internal documents and knowledge base, currently, the new PVA2 platform integration with Dynamics 365 Omnichannel for Customer Service isn't available. However, you can still achieve this by creating a classic PVA bot.
> 
> Do you know if this means that Copilot Studio is unable to handoff to Dynamics 365 at all right now?

Handoff to a live agent with Copilot Studio works. You can follow this documentation:

https://learn.microsoft.com/en-us/microsoft-copilot-studio/advanced-hand-off

Once the set up is done properly, only `const chatAdapter = chatSDK.createAdapter()` is needed.

**Comment by adam-boosted** [comment]
@xTEddie thank you so much for your response. The handoff has been configured correctly.

> Once the set up is done properly, only const chatAdapter = chatSDK.createAdapter() is needed.

What I'm trying to ascertain is, when and where precisely is this line needed when using botframework-webchat?

**Comment by xTEddie** [comment]
> @xTEddie thank you so much for your response. The handoff has been configured correctly.
> 
> > Once the set up is done properly, only const chatAdapter = chatSDK.createAdapter() is needed.
> 
> What I'm trying to ascertain is, when and where precisely (and with what parameters) is this line needed when using botframework-webchat?
> 
> I haven't been able to get it to work.

If handoff has been configured correctly with `Omnichannel for Customer Service`, you should be able to embed the widget snippet `<script data-org-id="" data-app-id="" data-org-url=""></script>` to your website/app which is the out-of-the-box chat widget to interact with the bot. If the set up is done properly, you should be able to use the chat widget to interact with the bot, then perform a handoff. 

The out-of-the-box chat widget offers customization capability: 

https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/develop-live-chat-widget#edit-live-chat-widget-script-to-enable-live-chat-widget-20

If the out-of-the-box chat widget, does not meet the user interface requirements, then you can decide to use `omnichannel-chat-sdk` to build a `custom` chat widget. This is where this `sdk` comes in. `omnichannel-chat-sdk` is a headless sdk which would allow you to build a custom widget from ground up. The `out-of-the-box` chat widget is built on top of this sdk with `BotFramework-WebChat`. 

`BotFramework-WebChat` and `Copilot Studio` is using `DirectLine` as messaging protocol. Typically you would have to use `createDirectLine()` to acquire the DirectLine `token` then pass it to `WebChat` to start a `Copilot Studio` conversation. 

```js
const directLine = createDirectLine({token: "YOUR_TOKEN"})
<ReactWebChat directLine={directLine} userID="YOUR_USER_ID" />
```

However,  `Omnichannel for Customer Service` is not using `DirectLine` messaging protocol. If we want to use `BotFramework-WebChat` with `Omnichannel for Customer Service`, the internal messaging API needs to be rewired. That's where `const chatAdapter = chatSDK.createAdapter()` comes in to render `BotFramework-WebChat`.

```js
const directLine = chatSDK.createChatAdapter(); // "mock" of DirectLine object with APIs rewired to integrate with `Omnichannel for Customer Service`
<ReactWebChat directLine={directLine} userID="YOUR_USER_ID" />
```

**Comment by adam-boosted** [comment]
Thanks so much for keeping this going @xTEddie.

We've customed the look of WebChat and are doing nearly exactly this:

```
const directLine = chatSDK.createChatAdapter(); // "mock" of DirectLine object with APIs rewired to integrate with `Omnichannel for Customer Service`
<ReactWebChat directLine={directLine} userID="YOUR_USER_ID" />
```

We're using the `sendEvent` hook internally to send contextual information into the copilot studio bot and, when we do that, the event/context never makes it to the bot, it times out. 

What we've also noticed is that using the chatAdapter (or the widget, which we don't want to use because of it's difficulty to customize) resulted in a much slower interaction experience with the bot (appears to use polling) than the directline experience which uses websockets and is lightning fast.

**Comment by xTEddie** [comment]
> Thanks so much for keeping this going @xTEddie.
> 
> We've customized the look of WebChat and are doing nearly exactly this:
> 
> ```
> const directLine = chatSDK.createChatAdapter(); // "mock" of DirectLine object with APIs rewired to integrate with `Omnichannel for Customer Service`
> <ReactWebChat directLine={directLine} userID="YOUR_USER_ID" />
> ```
> 
> We're using the `sendEvent` hook internally to send contextual information into the copilot studio bot and, when we do that, the event/context never makes it to the bot, it times out.
> 
> What we've also noticed is that using the chatAdapter (or the widget, which we don't want to use because of it's difficulty to customize) resulted in a much slower interaction experience with the bot (appears to use polling) than the directline experience which uses websockets and is lightning fast.

`sendEvent` is a concept in `DirectLine`. `Omnichannel for Customer Service` is using a different protocol, so sending event is not supported unfortunately. 

You can submit a feature request in the following forum:

https://experience.dynamics.com/ideas/categories/list/?category=e2570156-7f71-ed11-81ab-000d3a8c451e&forum=b68e50a6-88d9-e811-a96b-000d3a1be7ad

**Comment by adam-boosted** [comment]
> sendEvent is a concept in DirectLine. Omnichannel for Customer Service is using a different protocol, so sending event is not supported unfortunately.

It would be helpful to mark these `directline` options that can be given to `createChatAdapter` as deprecated or unsupported then. I've been trying to figure out a mental model of how these things work together for a while and those options sent me down the wrong path for a while. 

You've been great @xTEddie, thanks so much for the support and clarity about what's possible/what's not! 🙏

**Pull request closed without merging**
